# Base link in gazebo link_states
base_link_state: robot::base_link

# Target object to pick
object_name: coke_can

# Objects to spawn in the scene
planning_scene_objects:
  - name: coke_can
    link_state: coke_can::link
    dimensions: [0.16, 0.035]
    origin_compensation: [0., 0., 0.]

  - name: table
    link_state: table::link
    dimensions: [1.5, 0.8, 0.03]
    origin_compensation: [0., 0., 0.98]

# Place offset
place_offset: [0.0, 0.0, 0.0]
