controller_list:
- name: "scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

- name: "robotiq_2f_85_gripper_controller"
  action_ns: gripper_cmd
  default: True
  type: GripperCommand
  joints:
    - finger_joint
