name: upright_constraint
constraints:
- type: orientation
  frame_id: world
  link_name: tool0
  orientation: [deg(-90), deg(0), deg(-90)]
  tolerances: [deg(30), deg(360), deg(30)]
  parameterization: 1
  weight: 1.0
